/** Канонічні дії журналу аудиту. */
export const AuditAction = {
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_DELETED: 'ROLE_DELETED',
  ROLES_ASSIGNED: 'ROLES_ASSIGNED',
  USER_DELETED: 'USER_DELETED',
  SHIFT_APPROVED: 'SHIFT_APPROVED',
  SHIFT_REJECTED: 'SHIFT_REJECTED',
  SHIFT_DELETED: 'SHIFT_DELETED',
  SHIFT_AUTO_CLOSED: 'SHIFT_AUTO_CLOSED',
  SWAP_CREATED: 'SWAP_CREATED',
  SWAP_CLAIMED: 'SWAP_CLAIMED',
  SWAP_APPROVED: 'SWAP_APPROVED',
  SWAP_REJECTED: 'SWAP_REJECTED',
  SWAP_CANCELLED: 'SWAP_CANCELLED',
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
